version: '3.4'
services:
  autoheal:
    container_name: container_autoheal_nxtframework
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  springboot-nxtframework:
    container_name: container_springboot_nxtframework
    image: soyojoearth/nxtframework:0.1.0
    ports:
      - target: 8080
        published: 8686
        protocol: tcp
    restart: always
    volumes:
      - ./nxtframework_oss:/nxtframework_oss
    command: ["java", "-jar", "-Xms500m","-Xmx1500m", "/run.jar",
              "--spring.profiles.active=production",
              "--newxton.config.oss.localPath=/nxtframework_oss",
              "--spring.datasource.url=jdbc:mysql://192.168.0.100:3306/nxtframework?serverTimezone=Hongkong&useSSL=false&allowPublicKeyRetrieval=true",
              "--spring.datasource.username=root",
              "--spring.datasource.password=12345678"
    ]
  nginx:
    container_name: container_nginx_nxtframework
    image: nginx
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - ./http/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./http/ssl_cert.key:/ssl_cert.key:ro
      - ./http/ssl_cert.pem:/ssl_cert.pem:ro
    restart: always
    depends_on:
      - "springboot-nxtframework"

